"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";

type Slot = { time:string; format:string; role:string; objective:string; title:string; topic:string; hook:string; script:string; caption:string; visualDirection:string; cta:string; executionSteps:string[] };
type DayPlan = { day:string; mission:string; slots:Slot[] };
type AIProfile = { objective:string; currentStage:string; diagnosis:string; mainProblem:string; strategy:string; weeklyMission:string; nextAction:string; postingFrequency:string; postingFrequencyReason:string; weeklyContentCount:number; dailyContentCount:string; positioning:string; audience:string; conversionStrategy:string; contentPillars:string[]; tone:string[]; strengths:string[]; opportunities:string[]; thirtyDayPlan:{phase:string;focus:string;action:string;expectedSignal:string}[]; weeklyPlan:DayPlan[] };
type Profile = Record<string,any> & { aiProfile?:AIProfile|null; aiAnalyzedAt?:string|null };
type Me = { user:{name:string|null;email:string;phone?:string|null;strategicProfile:Profile|null;subscription?:any|null;socialAccounts?:{id:string;platform:string;username:string|null;connectedAt:string}[]} };

const tabs=[["home","🏠 Meu Instagram"],["strategy","🎯 Estratégia"],["week","📅 Minha semana"],["create","✨ Criar"],["results","📊 Resultados"],["profile","👤 Meu perfil"],["plans","💳 Planos"]] as const;
const fmtIcon:Record<string,string>={Story:"⚡",Foto:"📸",Post:"📸",Reel:"🎬",Vídeo:"🎬",Carrossel:"📚"};

export default function Dashboard(){
 const router=useRouter(); const [data,setData]=useState<Me|null>(null); const [loading,setLoading]=useState(true); const [tab,setTab]=useState("home"); const [analyzing,setAnalyzing]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/auth/me").then(async r=>{if(!r.ok){router.replace("/login");return null}return r.json()}).then(x=>{if(x){if(!x.user.strategicProfile?.onboardingCompletedAt){router.replace("/setup");return}setData(x)}}).finally(()=>setLoading(false))},[router]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.replace("/")}
 async function analyze(){setAnalyzing(true);setError("");try{const r=await fetch("/api/ai/analyze-profile",{method:"POST"});const x=await r.json();if(!r.ok){setError(x.error||"Não foi possível montar sua estratégia.");return}setData(d=>d?.user.strategicProfile?{...d,user:{...d.user,strategicProfile:{...d.user.strategicProfile,aiProfile:x.aiProfile,aiAnalyzedAt:x.aiAnalyzedAt}}}:d);await fetch("/api/content-drafts/sync",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({weeklyPlan:x.aiProfile.weeklyPlan})});setTab("home")}catch{setError("Não foi possível conectar à IA.")}finally{setAnalyzing(false)}}
 if(loading)return <main className="auth"><div className="authbox"><p className="muted">Carregando seu painel...</p></div></main>; if(!data)return null;
 const p=data.user.strategicProfile!; const raw=p.aiProfile; const ai=isCurrentStrategy(raw)?raw:null;
 let panel: ReactNode;
 if (!ai) panel = <SetupStrategy analyzing={analyzing} analyze={analyze} hasOldStrategy={Boolean(raw)} />;
 else if (tab === "home") panel = <Home ai={ai} onWeek={()=>setTab("week")} />;
 else if (tab === "strategy") panel = <Strategy ai={ai} />;
 else if (tab === "week") panel = <Week ai={ai} />;
 else if (tab === "create") panel = <Create />;
 else if (tab === "results") panel = <Results profile={p} />;
 else if (tab === "profile") panel = <ProfileView profile={p} router={router} />;
 else panel = <Plans subscription={data.user.subscription} />;
 return <main className="page"><nav className="nav"><div className="logo">MidiaNet<span>AI</span></div><button className="muted" onClick={logout} style={{background:"none",border:0,cursor:"pointer"}}>Sair</button></nav><section className="section" style={{paddingTop:28}}>
  <div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:8}}>{tabs.map(([id,label])=><button key={id} className={tab===id?"btn primary":"btn secondary"} onClick={()=>setTab(id)} style={{whiteSpace:"nowrap"}}>{label}</button>)}</div>
  <div style={{marginTop:24}}><div className="instagramStrip"><div className="igAvatar">◎</div><div style={{flex:1}}><strong>{data.user.socialAccounts?.[0]?.username ? "@"+data.user.socialAccounts[0].username : p.instagramProfileUrl || "Seu Instagram"}</strong><div className="small muted">{data.user.socialAccounts?.length ? "Conta conectada · métricas disponíveis quando sincronizadas" : "Conta ainda não conectada · você pode usar o MidiaNet AI sem conectar"}</div></div><div className="badge">{data.user.subscription?.status==="TRIALING"?"🧪 Teste ativo":"✓ Plano ativo"}</div></div><div style={{marginTop:24}}><div className="badge">Seu estrategista</div><h1 style={{fontSize:40,letterSpacing:-2,margin:"14px 0 8px"}}>Olá, {data.user.name||"criador"}.</h1><p className="muted">Você não precisa descobrir o que postar. O MidiaNet AI organiza o próximo passo.</p></div>
  {error&&<p className="small" style={{color:"#fda4af",marginTop:14}}>{error}</p>}
  </div>
  {panel}
 </section></main>;
}
function isCurrentStrategy(v:any):v is AIProfile{return Boolean(v&&typeof v==="object"&&typeof v.objective==="string"&&Array.isArray(v.weeklyPlan)&&(v.weeklyPlan.length===2||v.weeklyPlan.length===7)&&v.weeklyPlan.every((d:any)=>d&&Array.isArray(d.slots)&&d.slots.length===4))}
function SetupStrategy({analyzing,analyze,hasOldStrategy}:{analyzing:boolean;analyze:()=>void;hasOldStrategy:boolean}){return <div className="feature" style={{marginTop:24}}><div className="badge">{hasOldStrategy?"Atualização":"1º passo"}</div><h2 style={{marginTop:12}}>{hasOldStrategy?"Sua estratégia ganhou a nova programação.":"Vamos transformar seu perfil em um plano."}</h2><p className="muted" style={{marginTop:8,maxWidth:760}}>A IA vai montar diagnóstico, estratégia, semana completa e conteúdos prontos para você executar — 1 Story + 3 publicações principais por dia.</p><button className="btn primary" onClick={analyze} disabled={analyzing} style={{marginTop:18}}>{analyzing?"Analisando seu perfil...":hasOldStrategy?"Atualizar minha estratégia →":"Montar minha estratégia →"}</button></div>}
function Home({ai,onWeek}:{ai:AIProfile;onWeek:()=>void}){const today=useMemo(()=>ai.weeklyPlan?.[0],[ai.weeklyPlan]);return <><div className="grid3" style={{marginTop:22}}><Info title="🎯 Meu objetivo" value={ai.objective}/><Info title="📍 Onde estou" value={ai.currentStage}/><Info title="🚧 Principal problema" value={ai.mainProblem}/></div><div className="feature" style={{marginTop:18}}><div className="badge">🧭 Direção</div><h2 style={{marginTop:12}}>O que vamos fazer</h2><p style={{marginTop:8}}>{ai.strategy}</p><div className="grid3" style={{marginTop:18}}><Info title="📅 Frequência" value={ai.postingFrequency}/><Info title="🔥 Missão da semana" value={ai.weeklyMission}/><Info title="👉 Próximo passo" value={ai.nextAction}/></div></div>{today&&<div className="feature" style={{marginTop:18}}><div className="badge">🚀 Comece por aqui</div><h2 style={{marginTop:12}}>{today.day}</h2><p className="muted" style={{marginTop:6}}>{today.mission}</p><div className="grid2" style={{marginTop:14}}>{today.slots.map((s,i)=><MiniSlot key={i} slot={s}/>)}</div><button className="btn primary" onClick={onWeek} style={{marginTop:14}}>Ver minha semana completa →</button></div>}</>}
function Strategy({ai}:{ai:AIProfile}){return <div style={{marginTop:22}}><div className="feature"><div className="badge">🎯 Diagnóstico</div><h2 style={{marginTop:12}}>O perfil hoje</h2><p style={{marginTop:8}}>{ai.diagnosis}</p><p style={{marginTop:14}}><strong>Posicionamento:</strong> {ai.positioning}</p><p style={{marginTop:10}}><strong>Público:</strong> {ai.audience}</p><p style={{marginTop:10}}><strong>Conversão:</strong> {ai.conversionStrategy}</p></div><div className="feature" style={{marginTop:18}}><h2>🗓️ Plano de 30 dias</h2><div className="grid3" style={{marginTop:14}}>{ai.thirtyDayPlan.map((x,i)=><div className="card" key={i}><small>{x.phase}</small><strong style={{display:"block",marginTop:6}}>{x.focus}</strong><p style={{marginTop:8}}>{x.action}</p><p className="small muted" style={{marginTop:8}}>Sinal esperado: {x.expectedSignal}</p></div>)}</div></div></div>}
function Week({ai}:{ai:AIProfile}){const [selected,setSelected]=useState<{slot:Slot;day:string}|null>(null);return <div style={{marginTop:22}}><div className="feature"><div className="badge">📅 Execução</div><h2 style={{marginTop:12}}>Minha semana</h2><p className="muted" style={{marginTop:6}}>{ai.weeklyMission}</p><div className="grid3" style={{marginTop:14}}><Info title="📦 Conteúdos na semana" value={String(ai.weeklyContentCount||28)}/><Info title="📆 Conteúdos por dia" value={ai.dailyContentCount||"4 conteúdos por dia"}/><Info title="🧩 Estrutura diária" value="Story + Foto + Vídeo + Carrossel"/></div><div style={{marginTop:18}}>{ai.weeklyPlan.map((day,i)=><div className="card" key={i} style={{marginTop:12}}><div className="row-between"><div><strong style={{fontSize:19}}>{day.day}</strong><p className="small muted" style={{marginTop:5}}>{day.mission}</p></div><span className="badge">{day.slots.length} conteúdos</span></div><div style={{display:"grid",gap:8,marginTop:12}}>{day.slots.map((slot,j)=><button key={j} onClick={()=>setSelected({slot,day:day.day})} className="contentRow"><div><strong>{fmtIcon[slot.format]||"✨"} {j+1}. {slot.time} · {slot.format}</strong><div style={{marginTop:5}}>{slot.title}</div><div className="small muted" style={{marginTop:4}}>{slot.role} · {slot.objective}</div></div><span>→</span></button>)}</div></div>)}</div></div>{selected&&<ContentWorkspace slot={selected.slot} day={selected.day} onClose={()=>setSelected(null)}/>}</div>}
function MiniSlot({slot}:{slot:Slot}){return <div className="card2"><strong>{fmtIcon[slot.format]||"✨"} {slot.time} · {slot.format}</strong><div style={{marginTop:6}}>{slot.title}</div><div className="small muted" style={{marginTop:5}}>{slot.role}</div></div>}
function ContentWorkspace({slot:initialSlot,day,onClose}:{slot:Slot;day:string;onClose:()=>void}){const [slot,setSlot]=useState(initialSlot);const [instruction,setInstruction]=useState("");const [busy,setBusy]=useState(false);const [image,setImage]=useState("");const [imageBusy,setImageBusy]=useState(false);const [saved,setSaved]=useState(false);const [checked,setChecked]=useState<number[]>([]);
 async function refine(text?:string){const msg=(text||instruction).trim();if(!msg)return;setBusy(true);try{const r=await fetch("/api/ai/refine-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"refine",idea:{...slot,format:slot.format,title:slot.title},message:msg,history:[],format:slot.format})});const x=await r.json();if(r.ok&&x.result){setSlot(s=>({...s,title:x.result.title||s.title,format:x.result.format||s.format,objective:x.result.objective||s.objective,hook:x.result.hook||s.hook,script:x.result.script||s.script,caption:x.result.caption||s.caption,visualDirection:x.result.visualDirection||s.visualDirection,cta:x.result.cta||s.cta,topic:x.result.angle||s.topic,executionSteps:x.result.executionSteps||s.executionSteps}));setInstruction("")}}finally{setBusy(false)}}
 async function generateImage(){setImageBusy(true);try{const r=await fetch("/api/ai/generate-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:"Crie uma imagem para Instagram. Conteúdo: "+slot.title+". Tema: "+slot.topic+". Direção visual: "+slot.visualDirection+". Objetivo: "+slot.objective+". Estilo profissional, vertical 4:5, sem texto ilegível."})});const x=await r.json();if(r.ok)setImage(x.image||"")}finally{setImageBusy(false)}}
 return <div className="modalWrap"><div className="modal"><div className="row-between"><div><div className="badge">{fmtIcon[slot.format]||"✨"} {day} · {slot.time}</div><h2 style={{marginTop:10}}>{slot.title}</h2><p className="muted" style={{marginTop:5}}>{slot.role} · {slot.objective}</p></div><button className="btn secondary" onClick={onClose}>Fechar</button></div><div className="grid2" style={{marginTop:16}}><Detail title="🎯 Objetivo" text={slot.objective}/><Detail title="💡 Ideia/Tema" text={slot.topic}/></div><Detail title="🪝 Gancho" text={slot.hook}/><Detail title={slot.format==="Carrossel"?"📚 Estrutura do carrossel":"🎬 Roteiro"} text={slot.script}/><Detail title="✍️ Legenda pronta" text={slot.caption}/><Detail title="🎥 Como produzir" text={slot.visualDirection}/><Detail title="📣 CTA" text={slot.cta}/>{slot.executionSteps?.length>0&&<div className="card" style={{marginTop:12}}><strong>✅ Checklist</strong>{slot.executionSteps.map((x,i)=><button key={i} onClick={()=>setChecked(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])} className="checkRow"><span>{checked.includes(i)?"☑":"☐"}</span>{x}</button>)}</div>}{(slot.format==="Foto"||slot.format==="Carrossel")&&<div className="card" style={{marginTop:12}}><strong>✨ Criar com IA</strong><p className="small muted" style={{marginTop:6}}>Você pode produzir sozinho seguindo a orientação acima ou pedir uma referência visual para começar.</p><button className="btn primary" style={{marginTop:10}} onClick={generateImage} disabled={imageBusy}>{imageBusy?"Gerando imagem...":"Gerar imagem com IA"}</button>{image&&<img src={image} alt="Imagem gerada" style={{width:"100%",borderRadius:14,marginTop:12}}/>}</div>}<div className="card" style={{marginTop:12}}><strong>💬 O que você quer melhorar?</strong><div className="row" style={{gap:6,flexWrap:"wrap",margin:"10px 0"}}>{["Deixar mais natural","Mais chamativo","Mais focado em vendas","Quero outra ideia","Tenho outra visão"].map(x=><button key={x} className="pill" onClick={()=>refine(x)}>{x}</button>)}</div><textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Ex.: gostei, mas quero trocar o assunto e falar sobre..."/><button className="btn primary" style={{marginTop:10}} onClick={()=>refine()} disabled={busy}>{busy?"Ajustando...":"Melhorar com a IA"}</button></div><div className="row" style={{justifyContent:"flex-end",marginTop:14}}><button className="btn secondary" onClick={()=>setSaved(true)}>{saved?"✓ Salvo como aprovado":"Aprovar conteúdo"}</button></div></div></div>}
function Detail({title,text}:{title:string;text:string}){return <div className="card" style={{marginTop:12}}><strong>{title}</strong><p style={{marginTop:7,whiteSpace:"pre-line",lineHeight:1.55}}>{text||"—"}</p></div>}
function Create(){const [idea,setIdea]=useState("");const [loading,setLoading]=useState(false);const [options,setOptions]=useState<any[]>([]);const [error,setError]=useState("");async function multiply(){if(!idea.trim())return;setLoading(true);setError("");try{const r=await fetch("/api/ai/multiply-idea",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea})});const x=await r.json();if(!r.ok){setError(x.error||"Não foi possível multiplicar a ideia.");return}setOptions(x.options||[])}catch{setError("Não foi possível conectar à IA.")}finally{setLoading(false)}}return <div style={{marginTop:22}}><div className="feature"><div className="badge">✨ Criar</div><h2 style={{marginTop:12}}>Você traz a ideia. A IA encontra os caminhos.</h2><p className="muted" style={{marginTop:7}}>Escreva uma ideia do jeito que vier à cabeça. Não precisa criar prompt.</p><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Ex.: quero falar sobre os erros que pequenos negócios cometem no Instagram..." style={{marginTop:16,minHeight:120}}/><button className="btn primary" style={{marginTop:12}} onClick={multiply} disabled={loading}>{loading?"Encontrando caminhos...":"🚀 Multiplicar minha ideia"}</button>{error&&<p className="small" style={{color:"#fda4af",marginTop:10}}>{error}</p>}</div>{options.length>0&&<div style={{marginTop:18}}><h2>5 formas de transformar essa ideia</h2><p className="muted" style={{marginTop:6}}>Escolha um caminho, depois refine com a IA até ficar com a sua cara.</p><div style={{display:"grid",gap:12,marginTop:14}}>{options.map((o,i)=><div className="card" key={i}><div className="row-between"><div><span className="badge">{i+1} · {o.format}</span><h3 style={{marginTop:9}}>{o.title}</h3></div><span className="small muted">{o.angle}</span></div><p style={{marginTop:9}}><strong>🪝 {o.hook}</strong></p><p className="small muted" style={{marginTop:7}}>{o.objective}</p><button className="btn secondary" style={{marginTop:10}} onClick={()=>{setIdea(o.title+" — "+o.hook);setOptions([])}}>Usar esta ideia</button></div>)}</div></div>}</div>}
function Plans({subscription}:{subscription:any}){const end=subscription?.trialEndsAt?new Date(subscription.trialEndsAt):null;const days=end?Math.max(0,Math.ceil((end.getTime()-Date.now())/86400000)):0;return <div style={{marginTop:22}}><div className="feature"><div className="badge">💳 Seu acesso</div><h2 style={{marginTop:12}}>{subscription?.status==="TRIALING"?"Teste gratuito ativo":"Plano MidiaNet AI"}</h2><p className="muted" style={{marginTop:7}}>{subscription?.status==="TRIALING"?`Você tem ${days} dia(s) restante(s) no teste.`:"Seu plano atual aparece aqui."}</p><div className="grid3" style={{marginTop:16}}><div className="card"><small>TESTE</small><strong>2 dias</strong><p className="small muted">8 conteúdos + 2 imagens</p></div><div className="card"><small>MENSAL</small><strong>Completo</strong><p className="small muted">Estratégia, criação e evolução.</p><button className="btn primary" style={{marginTop:10}} onClick={()=>alert("Checkout mensal será conectado ao seu provedor de pagamento.")}>Escolher mensal</button></div><div className="card"><small>ANUAL</small><strong>Completo</strong><p className="small muted">Estratégia, criação e evolução.</p><button className="btn primary" style={{marginTop:10}} onClick={()=>alert("Checkout anual será conectado ao seu provedor de pagamento.")}>Escolher anual</button></div></div></div></div>}
function Results({profile}:{profile:Profile}){const [data,setData]=useState<any>(null);useEffect(()=>{fetch("/api/metrics/summary").then(r=>r.json()).then(setData)},[]);const latest=data?.latest;const previous=data?.previous;const delta=(key:string)=>latest&&previous&&latest[key]!=null&&previous[key]!=null?latest[key]-previous[key]:null;return <div style={{marginTop:22}}><div className="feature"><div className="badge">📊 Evolução do perfil</div><h2 style={{marginTop:12}}>{data?.connected?"Acompanhe o que está mudando":"Seu painel de evolução"}</h2><p className="muted" style={{marginTop:7}}>{data?.connected?"Dados da conta @"+(data.account?.username||"Instagram")+".":"Conecte seu Instagram para transformar esta área em um painel real de crescimento."}</p><div className="grid3" style={{marginTop:16}}><Metric title="Seguidores" value={latest?.followers} change={delta("followers")}/><Metric title="Alcance" value={latest?.reach} change={delta("reach")}/><Metric title="Visualizações" value={latest?.views} change={delta("views")}/><Metric title="Curtidas" value={latest?.likes} change={delta("likes")}/><Metric title="Comentários" value={latest?.comments} change={delta("comments")}/><Metric title="Compartilhamentos" value={latest?.shares} change={delta("shares")}/></div></div><div className="feature" style={{marginTop:18}}><h2>📈 Histórico</h2>{data?.snapshots?.length?<div style={{marginTop:12,display:"grid",gap:8}}>{data.snapshots.map((x:any)=><div className="card" key={x.id}><div className="row-between"><strong>{new Date(x.capturedAt).toLocaleDateString("pt-BR")}</strong><span className="small muted">{x.followers??"—"} seguidores · {x.views??"—"} views</span></div></div>)}</div>:<p className="muted" style={{marginTop:8}}>Ainda não há snapshots. Quando a integração oficial estiver conectada e os dados começarem a chegar, esta área mostrará a evolução por dia/semana.</p>}</div></div>}
function Metric({title,value,change}:{title:string;value?:number|null;change?:number|null}){return <div className="feature"><small className="muted">{title}</small><p style={{marginTop:8,fontSize:28,fontWeight:800}}>{value==null?"—":value.toLocaleString("pt-BR")}</p><p className="small muted" style={{marginTop:4}}>{change==null?"Sem comparação":(change>=0?"+":"")+change.toLocaleString("pt-BR")+" desde o snapshot anterior"}</p></div>}
function ProfileView({profile,router}:{profile:Profile;router:ReturnType<typeof useRouter>}){const fields=[["Instagram",profile.instagramProfileUrl],["Tipo de negócio",profile.businessType],["Nicho",profile.niche],["Oferta",profile.offer],["Objetivo",profile.objective],["Objetivos secundários",Array.isArray(profile.secondaryObjectives)?profile.secondaryObjectives.join(", "):""],["Resultado desejado",profile.desiredOutcome],["Público",profile.audience],["Idade do público",profile.audienceAge],["Localização do público",profile.audienceLocation],["Interesses",profile.audienceInterests],["Dores e desejos",profile.audiencePainPoints],["Posicionamento",profile.desiredPositioning],["Personalidade",profile.brandPersonality],["Estilo",profile.contentStyle],["Formatos",Array.isArray(profile.contentPreferences)?profile.contentPreferences.join(", "):""],["Frequência",profile.postingFrequency],["Monetização",profile.monetization],["Conversão",profile.conversionGoal],["Funil",profile.salesFunnel],["Meta de 90 dias",profile.ninetyDayGoal],["Definição de sucesso",profile.successDefinition],["Diferenciais",profile.differentiators],["Desafios atuais",profile.currentChallenges]];return <div style={{marginTop:22}}><div className="feature"><div className="badge">👤 Meu perfil</div><h2 style={{marginTop:12}}>{profile.niche||"Seu nicho"}</h2><p style={{marginTop:8}}><strong>Oferta:</strong> {profile.offer||"—"}</p><p style={{marginTop:8}}><strong>Objetivo:</strong> {profile.objective||profile.desiredOutcome||"—"}</p><p style={{marginTop:8}}><strong>Posicionamento:</strong> {profile.desiredPositioning||"—"}</p><div className="profileGrid" style={{marginTop:18}}>{fields.map(([label,value])=><div className="card" key={label}><small className="muted">{label}</small><p style={{marginTop:6,whiteSpace:"pre-line"}}>{String(value||"—")}</p></div>)}</div><button className="btn secondary" onClick={()=>router.push("/setup")} style={{marginTop:16}}>Editar meu diagnóstico</button></div></div>}
function Info({title,value}:{title:string;value:string}){return <div className="feature"><small className="muted">{title}</small><p style={{marginTop:8,fontSize:17,lineHeight:1.45}}>{value||"—"}</p></div>}
